export const LOCATIONS = {
  STAFFORD: {
    name: "STAFFORD/SUGAR LAND",
    address: "12603 Southwest Fwy Ste 101, Stafford, TX 77477",
    zip: "77477",
  },
  SPRING: {
    name: "SPRING",
    address: "17320 Red Oak Dr, Ste 102, Houston, TX 77090",
    zip: "77090",
  },
  KATY: {
    name: "KATY",
    address: "24217 Kingsland Blvd, Katy, TX 77494",
    zip: "77494",
  },
  SOUTHFIELD: {
    name: "SOUTHFIELD",
    address: "26400 W 12 Mile Rd Ste 25, Southfield, MI 48034",
    zip: "48034",
  },
};

export const SERVICES = {
  therapy: {
    title: "Therapy Services",
    services: {
      physical: {
        name: "Physical Therapy",
        icon: "🏃‍♂️",
        description:
          "Physical Therapy (PT) is care that aims to ease pain and help you function, move, and live better. Your personal physical therapy begins with a comprehensive evaluation of functional limitations and areas of pain. Our team of expert physical therapists will design a treatment plan based on your work-related needs and goals.",
        keywords: [
          "pt",
          "physiotherapy",
          "physical rehab",
          "physio",
          "rehabilitation",
        ],
        details: [
          "Personalized treatment plans",
          "Manual therapy techniques", 
          "Therapeutic exercises",
          "Pain management",
          "Functional training",
        ],
        duration: "45-60 minutes",
        frequency: "2-3 sessions per week",
      },
      occupational: {
        name: "Occupational Therapy",
        icon: "🔧",
        description:
          "Occupational therapists treat injured, ill, or disabled patients through the therapeutic use of everyday activities. They help these patients develop, recover, improve, as well as maintain the skills needed for daily living and working.",
      },
      aquatic: {
        name: "Aquatic Therapy",
        icon: "🏊‍♂️",
        description:
          "With aquatic therapy at Theramedic, low-impact exercises paired with water resistance help reduce pain, improve mobility, and build strength for a faster and more comfortable recovery.",
      },
      speech: {
        name: "Speech Language Therapy",
        icon: "🗣️",
        description:
          "If you're experiencing difficulties with speech, language, or swallowing, our speech therapists provide specialized techniques to help you communicate effectively and regain independence in eating and drinking.",
      },
      pediatric: {
        name: "Pediatric Therapy", 
        icon: "👶",
        description:
          "Theramedic's pediatric therapy helps children reach developmental milestones, improve motor and communication skills, and build confidence for a brighter, more active future.",
      },
      telerehab: {
        name: "Tele-Rehab",
        icon: "💻",
        description:
          "Experience the convenience of tele-rehab at Theramedic, where expert therapy is delivered to your home, improving mobility, strength, and recovery, while offering personalized care wherever you are.",
      },
    },
  },
  recovery: {
    title: "Recovery Services",
    services: {
      auto: {
        name: "Auto Injury Rehab",
        icon: "🚗",
        description:
          "Expert rehabilitation for auto accident injuries, focusing on reducing pain and rebuilding strength. Our targeted therapy helps restore movement, function, and independence through proven techniques.",
      },
      sports: {
        name: "Sport Injuries",
        icon: "⚽",
        description:
          "Effective rehabilitation for sports injuries, focused on pain relief, mobility restoration, and performance. Our goal is to get athletes back to their sport stronger, more resilient, and ready to excel.",
      },
      cognitive: {
        name: "Cognitive Rehab",
        icon: "🧠",
        description:
          "Targeted therapy to improve cognitive function, memory, and focus. Our personalized approach helps individuals regain clarity, confidence, and independence, enhancing daily life.",
      },
      worker: {
        name: "Work Injury",
        icon: "⚒️",
        description:
          "Personalized therapy to relieve pain, restore function, and promote a safe return to work. We help improve strength, mobility, and confidence, ensuring you're equipped for a successful and lasting recovery.",
      },
      vestibular: {
        name: "Vestibular Rehab",
        icon: "🌀",
        description:
          "Targeted balance therapy to alleviate dizziness, improve stability, and rebuild confidence in movement. This treatment helps patients regain control over their coordination and restore comfort in everyday activities.",
      },
      fce: {
        name: "Functional Capacity Evaluation (FCE)",
        icon: "📊",
        description:
          "Detailed evaluation to assess physical capabilities, supporting personalized rehab planning and work readiness. FCE aids in designing safe, targeted therapy for effective recovery and return to daily tasks.",
      },
      stroke: {
        name: "Stroke Rehab",
        icon: "🫀",
        description:
          "Holistic therapy to restore strength, mobility, and independence after a stroke. Our approach helps patients regain essential functions, supporting an improved quality of life and return to daily activities.",
      },
    },
  },
  rehab: {
    title: "Rehab Services",
    services: {
      dryneedling: {
        name: "Dry Needling",
        icon: "💉",
        description:
          "Dry Needling is a technique that involves inserting thin needles into trigger points within muscles to relieve pain and improve movement. This therapy is highly effective for reducing muscle tension, improving blood flow, and enhancing overall recovery.",
        details: [
          "Precise needle placement for pain relief",
          "Trigger point therapy for muscle tension",
          "Improved flexibility and mobility",
          "Enhanced blood circulation for faster recovery",
          "Relief for chronic pain and stiffness",
        ],
        duration: "30-45 minutes",
        frequency: "1-2 sessions per week",
        // keywords: [],
      },
      cupping: {
        name: "Cupping Therapy",
        icon: "🔄",
        description: "Cupping Therapy is a healing technique that uses special cups to create suction on the skin, drawing blood to the surface and promoting deep tissue healing. This therapy is highly effective for reducing muscle tension, improving circulation, and enhancing recovery while releasing toxins from the body.",
        details: [
          "Strategic cup placement for optimal healing",
          "Myofascial release through negative pressure",
          "Improved circulation and lymphatic drainage",
          "Enhanced recovery and reduced inflammation",
          "Relief for chronic pain and muscle stiffness"
        ],
        duration: "30-45 minutes",
        frequency: "1-2 sessions per week",
        // keywords: []
      },
      paraffin: {
        name: "Paraffin Wax Therapy",
        icon: "🔥",
        description: "Paraffin Wax Therapy is a luxurious heat treatment that involves dipping the hands, feet, or other body parts into warm, soothing wax. This therapy provides deep, penetrating heat that helps improve circulation, relieve joint pain, and intensely moisturize and soften the skin.",
        details: [
          "Therapeutic warm wax application for deep heat penetration",
          "Improved joint mobility and pain relief",
          "Enhanced circulation to targeted areas", 
          "Intensive skin hydration and softening",
          "Relief for arthritis and stiff joints"
        ],
        duration: "15-20 minutes",
        frequency: "1-2 sessions per week",
        // keywords: []
      },
      normatec: {
        name: "NormaTec Compression Therapy",
        icon: "🦿",
        description: "NormaTec Compression Therapy uses advanced pneumatic compression technology to enhance recovery and performance. This innovative system applies sequential pulse compression to your limbs, effectively flushing out metabolic waste and reducing muscle soreness while improving circulation.",
        details: [
          "Dynamic compression for enhanced recovery",
          "Sequential pulse technology targeting specific muscle groups",
          "Improved circulation and lymphatic drainage",
          "Reduced muscle soreness and fatigue",
          "Accelerated recovery between training sessions"
        ],
        duration: "20-30 minutes",
        frequency: "2-3 sessions per week",
        // keywords: []
      }
    },
  },
};

export const PAIN_AREAS = {
  head_pain: {
    display: "Head Pain",
    icon: "🧠",
    treatments: ["Manual therapy", "Exercise therapy", "Posture correction"],
    description:
      "Our specialists address headaches, migraines, and TMJ disorders with targeted treatments.",
  },
  shoulder_pain: {
    display: "Shoulder Pain",
    icon: "💪",
    treatments: [
      "Manual therapy",
      "Strengthening exercises",
      "Stretching",
      "Posture correction",
      "Joint mobilization",
    ],
    description:
      "We provide targeted treatments for rotator cuff injuries, frozen shoulder, and other shoulder-related conditions to improve mobility and reduce pain.",
  },
  back_pain: {
    display: "Back Pain",
    icon: "⬆️",
    treatments: [
      "Spinal mobilization",
      "Core strengthening",
      "Postural education",
    ],
    description:
      "Our comprehensive approach targets both relief and prevention of recurring back pain.",
  },
  neck_pain: {
    display: "Neck Pain",
    icon: "↕️",
    treatments: [
      "Manual therapy",
      "Therapeutic exercise",
      "Ergonomic training",
    ],
    description:
      "We address pain from tech neck, whiplash, and chronic conditions with specialized care.",
  },
  hip_pain: {
    display: "Hip Pain",
    icon: "🦵",
    treatments: ["Joint mobilization", "Strengthening", "Movement retraining"],
    description:
      "Our therapists specialize in improving mobility and reducing hip discomfort.",
  },
  elbow_pain: {
    display: "Elbow Pain",
    icon: "💪",
    treatments: [
      "Manual therapy",
      "Eccentric training",
      "Activity modification",
    ],
    description:
      "We provide effective treatment for tennis elbow, golfer's elbow and other conditions.",
  },
  pelvic_floor: {
    display: "Pelvic Floor",
    icon: "⚠️",
    treatments: ["Muscle retraining", "Biofeedback", "Behavioral strategies"],
    description:
      "Our specialized therapists address pelvic pain and dysfunction with expert care.",
  },
  hand_wrist_pain: {
    display: "Hand/Wrist Pain",
    icon: "✋",
    treatments: ["Joint mobilization", "Nerve gliding", "Therapeutic exercise"],
    description:
      "We treat carpal tunnel, arthritis, and post-surgical conditions of the hand and wrist.",
  },
  knee_pain: {
    display: "Knee Pain",
    icon: "🦿",
    treatments: ["Joint mobilization", "Strengthening", "Movement retraining"],
    description:
      "Our therapists address injuries, arthritis, and post-surgical recovery with specialized care.",
  },
  foot_ankle_pain: {
    display: "Foot/Ankle Pain",
    icon: "👣",
    treatments: ["Joint mobilization", "Balance training", "Gait analysis"],
    description:
      "We provide effective treatment for plantar fasciitis, sprains, and chronic instability.",
  },
};

export const FAQs = {
  greeting: [
    "Hi there! I'm your Theramedic Rehab! assistant.\nHow can I help you feel better today?",
    "Welcome to our Theramedic Rehab! What brings you in today?",
  ],
  hours: [
    "⏰ We're here for you:",
    "Monday-Friday: 9:00 AM - 6:00 PM",
    "Weekends: Closed",
  ],
  insurance: [
    "We accept most major insurance plans including Blue Cross, Aetna, UnitedHealthcare, Cigna, and Medicare.",
    "To check your coverage, I'll need a few quick details.",
  ],
  locations: [
    "We have 4 convenient locations to serve you:",
    "🏢 STAFFORD/SUGAR LAND: 12603 Southwest Fwy, TX 77477",
    "🏢 SPRING: 17320 Red Oak Dr, TX 77090", 
    "🏢 KATY: 24217 Kingsland Blvd, TX 77494",
    "🏢 SOUTHFIELD: 26400 W 12 Mile Rd, MI 48034",
    "Which is most convenient for you?",
  ],
  parking: [
    "🅿️ Free parking is available at all four locations: ",
    "STAFFORD/SUGAR LAND,\n\n SPRING,\n\n KATY,\n\n SOUTHFIELD ",
    "All locations have accessible/handicap spots near entrance."
  ],
  painResponse: [
    "Our therapists are highly trained to address your specific condition, utilizing evidence-based techniques to provide effective relief.",
    "Let's schedule you with the right specialist who can help you get relief quickly.",
  ],
  insuranceQuery: [
    "Thanks for asking! Insurance coverage can vary based on your plan and location. To provide accurate details, please share your information via the form below, our team will contact you shortly so we can assist you faster.",
  ],
  treatmentPlan: [
    "Great question! Treatment plans are personalized to meet your unique needs and goals. To help us design the best approach for you, kindly share your details here, Our team will review your case and reach out with tailored recommendations!",
  ],
  paymentPlans: [
    "We appreciate you asking! We provide flexible options to suit different needs, and our team will gladly share details based on your situation. For a quick response, please fill out this short form:",
  ],
  costQuery: [
    "Costs can vary depending on your treatment plan and insurance coverage. To give you a clear estimate, we'll need a few details about your needs. Share your info here, and our team will contact you shortly.",
  ],
  genericAppointment: [
    "Thanks for your interest! To streamline your experience, please share your details via our form. Our team will review your request and contact you.",
  ],
  referral: [
    "Thanks for asking! Requirements vary, and we'll clarify everything for you. To simplify the process, fill out the form below:",
  ],
  sessionLength: [
    "Great question! Session length varies based on your needs, and we'll ensure it aligns with your recovery goals. To share specifics, kindly fill out this quick form:",  
  ],
  conditionsTreated: [
    "Thanks for reaching out! We address a wide range of below conditions.",
    "Your care plan will be personalized. To guide you better, share your concerns via the form below:",
  ],
  startTreatment: [
    "We're eager to help you begin! To check availability and fast-track your first session, please share your details here:",
  ],
  firstAppointment: [
    "Great question! We'll send you a personalized checklist based on your needs. Share your details here to get started:",
  ],
};

export const SPELLING_CORRECTIONS = {
  // Physical Therapy variations - Refactored to Array
  "physical therapy": [
    "physical therap",
    "physical theraphy",
    "physical therapee",
    "physical therapi",
    "physical tharapy",
    "physical thrapy",
    "physical theray",
    "phys therapy",
    "phys therap",
    "phys thera",
    "phisical therapy",
    "phisical theapy",
    "phisical thrpy",
    "phisicl therapy",
    "phisicl therpy",
    "physio",
    "physio therapy",
    "physiotherapy",
    "physioterapy",
    "physioterapee",
    "physiotherapi",
    "physiothrapy",
    "fisiotherapy",
    "fisiotherapi",
    "fisiotherapee",
    "fisical therapy",
    "fisioterapy",
    "fizical therapy",
    "fyzical therapy",
    "pt",
    "p.t.",
    "p t",
    "physical",
    "phisical",
    "manual",
    "therapeutic exercise",
    "movement",
    "rehabilitation",
    "mobility",
    "exercise",
    "movement specialist",
  ],

  // Occupational Therapy variations - Refactored to Array
  "occupational therapy": [
    "occupational therap",
    "occupational theraphy",
    "occupational therapi",
    "occupational tharapy",
    "occupational thrapy",
    "occupational theray",
    "occ therapy",
    "occ therap",
    "ocupational therapy",
    "ocupational therap",
    "ocupationl therapy",
    "ocupational thrapy",
    "ocupational therpy",
    "ocupationl",
    "ocupationel",
    "occupationl",
    "ocup therapy",
    "ocup therap",
    "occupationel",
    "ocuppational",
    "ocupational",
    "ot therapy",
    "o.t therapy",
    "o t",
    "occupational",
    "adl training",
    "activities of daily living",
    "daily living skills",
    "functional training",
    "ergonomic training",
    "work hardening",
    "hand therapy",
    "adaptive equipment",
  ],

  // Aquatic Therapy variations - Refactored to Array
  "aquatic therapy": [
    "aquatic therap",
    "aquatic theraphy",
    "aquatic therapi",
    "aquatic tharapy",
    "aquatic thrapy",
    "aquatic theray",
    "aqua therapy",
    "aqua therap",
    "aquatherapy",
    "aqua thera",
    "aquarehab",
    "aqua rehab",
    "water therapy",
    "water therap",
    "water pt",
    "pool therapy",
    "pool exercise",
    "pool rehab",
    "swimming therapy",
    "swim therapy",
    "hidro therapy",
    "hydrotherap",
    "hydrotherapy",
    "hydro rehab",
    "water exercise",
    "water rehab",
    "water",
    "hydro",
    "aquatic",
    "aqua",
    // Added new conditions
    "circulation",
    "circulation problem",
    "circulation issues",
    "poor circulation",
    "blood flow",
    "heart disease",
    "heart condition",
    "cardiac rehab",
    "cardiovascular",
    "muscle spasm",
    "muscle spasms",
    "muscle cramp",
    "muscle pain",
    "neurological",
    "neurological injury",
    "nerve injury",
    "nerve damage",
    "neuro rehab",
  ],

  // Speech Therapy variations - Refactored to Array
  "Speech Language Therapy": [
    "speech therap",
    "speech theraphy",
    "speech therapi",
    "speech tharapy",
    "speech thrapy",
    "speech theray",
    "speach therapy",
    "speach therap",
    "speach thera",
    "speach",
    "speec",
    "speetch",
    "speach language",
    "speech lang",
    "speech language",
    "speech pathology",
    "speach lang therapy",
    "speach pathology",
    "speech-language",
    "swallowing therapy",
    "dysphagia therapy",
    "communication therapy",
    "language therapy",
    "articulation therapy",
    "voice therapy",
    "slp",
    "s.l.p.",
    "s l p",
    "speech",
  ],

  // Pediatric Therapy variations - Refactored to Array
  "pediatric therapy": [
    "pediatric therap",
    "pediatric theraphy",
    "pediatric therapi",
    "pediatric tharapy",
    "pediatric thrapy",
    "pediatric theray",
    "pediatrik",
    "pediatrik therapy",
    "paediatric",
    "paediatric therapy",
    "child therapy",
    "children therapy",
    "childrens therapy",
    "kid therapy",
    "kids therapy",
    "child development",
    "developmental therapy",
    "childhood therapy",
    "pediatric pt",
    "pediatric ot",
    "pediatric st",
    "peds therapy",
    "peeds therapy",
    "peds",
    "kids pt",
    "childrens pt",
    "infants therapy",
    "toddler therapy",
    "youth therapy",
    "pediatric",
  ],

  // Tele-rehab variations - Refactored to Array
  "Tele-Rehab": [
    "tele-rehab", // Included for completeness, but already base form
    "telerehab",
    "tele rehab",
    "telereahb",
    "tele-rehabilitation",
    "telerehabilitation",
    "teletherapy",
    "tele therapy",
    "tele-therapy",
    "virtual therapy",
    "virtual pt",
    "virtual rehab",
    "virtual rehabilitation",
    "online therapy",
    "online pt",
    "online rehab",
    "remote pt",
    "remote therapy",
    "remote rehab",
    "telehealth",
    "telehealth therapy",
    "telemedicine",
    "digital therapy",
    "distance therapy",
    "video therapy",
    "zoom therapy",
    "home therapy",
  ],

  // Auto Injury Rehab variations - Refactored to Array
  "auto injury rehab": [
    "auto",
    "auto injury",
    "auto injury therapy",
    "auto injury treatment",
    "auto injury rehabilitation",
    "auto accident",
    "auto accident therapy",
    "auto accident rehab",
    "auto accident rehabilitation",
    "car accident",
    "car accident therapy",
    "car accident rehab",
    "car accident rehabilitation",
    "car injury",
    "motor vehicle",
    "motor vehicle accident",
    "mva",
    "mva rehab",
    "mva therapy",
    "car crash",
    "car crash therapy",
    "car crash rehab",
    "traffic accident",
    "vehicle injury",
    "automobile injury",
    "whiplash rehab",
    "collision injury",
  ],

  // Sport Injuries variations - Refactored to Array
  "sport injuries": [
    "sport injuries", // Included for completeness
    "sports",
    "sports injury",
    "sports injuries",
    "sports injury rehab",
    "sports injury therapy",
    "sports injury treatment",
    "sports injury rehabilitation",
    "sport injury",
    "sport injury rehab",
    "sport injury therapy",
    "sport injury treatment",
    "athletic injury",
    "athletic injuries",
    "athletic rehab",
    "athletic therapy",
    "athletic rehabilitation",
    "sports rehab",
    "sports rehabilitation",
    "sports therapy",
    "sports related",
    "athlet rehab",
    "athlete therapy",
    "running injury",
    "tennis injury",
    "golf injury",
    "basketball injury",
    "football injury",
    "soccer injury",
    "performance rehab",
  ],

  // Cognitive Rehab variations - Refactored to Array
  "cognitive rehab": [
    "cognitive rehab", // Included for completeness
    "cognitive",
    "cognitive therapy",
    "cognitive rehabilitation",
    "cognitive treatment",
    "congnitive",
    "congnitive rehab",
    "congnitive therapy",
    "cognative",
    "cognative rehab",
    "cognative therapy",
    "brain injury",
    "brain injury rehab",
    "brain injury therapy",
    "brain injury treatment",
    "brain injury rehabilitation",
    "tbi",
    "tbi rehab",
    "tbi therapy",
    "tbi treatment",
    "traumatic brain injury",
    "concussion",
    "concussion rehab",
    "concussion therapy",
    "concussion treatment",
    "memory therapy",
    "memory rehab",
    "mental rehab",
    "brain training",
    "conitive therapy",
    "neurological therapy",
    "neuro rehab",
    "neurotherapy",
  ],

  // Work Injury variations - Refactored to Array
  "work injury": [
    "work injury", // Included for completeness
    "worker",
    "worker injury",
    "worker injury rehab",
    "worker injury therapy",
    "worker injury treatment",
    "worker injury rehabilitation",
    "workers injury",
    "workers injury rehab",
    "workers injury therapy",
    "workcomp",
    "work comp",
    "workers comp",
    "workers compensation",
    "workmans comp",
    "workmans compensation",
    "workman comp",
    "workman compensation",
    "job injury",
    "job injury rehab",
    "job injury therapy",
    "work injury rehab",
    "work related injury",
    "workplace injury",
    "workplace accident",
    "occupational injury",
    "occupational accident",
    "industrial injury",
    "industrial accident",
    "on the job injury",
  ],

  // Vestibular Rehab variations - Refactored to Array
  "vestibular rehab": [
    "vestibular rehab", // Included for completeness
    "vestibular",
    "vestibular therapy",
    "vestibular rehabilitation",
    "vestibular treatment",
    "vestibular training",
    "vestibular exercise",
    "vestbular",
    "vestbular rehab",
    "vestbular therapy",
    "balance",
    "balance therapy",
    "balance treatment",
    "balance rehabilitation",
    "balance training",
    "balance exercises",
    "dizziness",
    "dizziness therapy",
    "dizziness treatment",
    "dizziness rehab",
    "dizzy",
    "dizzy therapy",
    "dizzy treatment",
    "vertigo",
    "vertigo therapy",
    "vertigo treatment",
    "vertigo rehab",
    "bppv",
    "bppv treatment",
    "inner ear",
    "inner ear therapy",
  ],

  // Functional Capacity Evaluation variations - Refactored to Array
  "Functional Capacity Evaluation (FCE)": [
    "functional capacity evaluation", // Included for completeness
    "functional capacity eval",
    "functional capacity",
    "functional capacity test",
    "functional capacity testing",
    "functional capacity assessment",
    "fce",
    "f.c.e.",
    "f c e",
    "functional eval",
    "functional evaluation",
    "functional assessment",
    "capacity eval",
    "capacity evaluation",
    "capacity assessment",
    "work capacity",
    "work capacity evaluation",
    "work capacity assessment",
    "functional testing",
    "job capacity",
    "job capacity evaluation",
    "return to work evaluation",
    "return to work assessment",
    "physical capacity",
    "physical capacity evaluation",
  ],

  // Stroke Rehab variations - Refactored to Array
  "stroke rehab": [
    "stroke rehab", // Included for completeness
    "stroke",
    "stroke therapy",
    "stroke rehabilitation",
    "stroke treatment",
    "stroke recovery",
    "stroke exercise",
    "cva",
    "cva therapy",
    "cva rehabilitation",
    "cva treatment",
    "cva recovery",
    "cerebral vascular",
    "cerebral vascular accident",
    "cerebrovascular",
    "cerebrovascular accident",
    "post stroke",
    "post stroke therapy",
    "post stroke rehab",
    "post stroke rehabilitation", 
    "post stroke recovery",
    "hemiplegia",
    "hemiplegia therapy",
    "hemiplegia rehab",
    "hemiplegia rehabilitation",
    "hemiparesis",
    "hemiparesis therapy",
    "hemiparesis rehab",
    "hemiparesis rehabilitation",
    "brain attack",
    "neurological rehab",
  ],

  // Dry Needling variations 
  "Dry Needling": [
    "dry needling therapy",
    "needling",
    "pinpoint",
    "acupuncture", 
    "dyr needling therapy",
    "dry neelding therapy",
    "dyr neelding therapy",
    "dry needlin therapy",
    "dry neding therapy",
    "ry needling therapy",
    "ddry needling therapy",
    "dry needlingg therapy",
    "dry needlingg theraphy",
    "dri needling therapy",
    "dry needlin therapy",
    "drr needling therapy",
    "dry nedling therapy",
    "dry needljng therapy"
  ],

  // Cupping Therapy variations
  "Cupping Therapy": [
    "vacuum therapy",
    "vaccuum therapy", 
    "vacum therapy",
    "cupping theraapy",
    "cupping theryapy",
    "cuping therapy",
    "cupping therpy",
    "cuppin therapy",
    "cupping theraoy", 
    "cuppping therapy",
    "cuppingg therapy",
    "cupping theraphy",
    "cuiping therapy",
    "cuppin therapy",
    "cupping theraapy",
    "cuppong therapy",
    "cuppinh therapy",
    "cupping tjerapy"
  ],

  // Paraffin Wax Therapy variations
  "Paraffin Wax Therapy": [
    "heat therapy",
    "wax therapy",
    "paraffin wxa therapy",
    "paraffin txa therapy", 
    "parafinn wax therapy",
    "paraffin wax therap",
    "parafin wax therapy",
    "parafin waz therapy",
    "paraffin waxx therapy",
    "paraffin wwax therapy",
    "parrafin wax therapy",
    "parafin waks therapy",
    "paraffin waks therapy",
    "parafin wax therapyy",
    "paraffin waz therapy",
    "paraffin xax therapy",
    "pqraffin wax therapy"
  ],

  // Normatec Compression Therapy variations
  "NormaTec Compression Therapy": [
    "air compression",
    "air therapy",
    "compression therapy",
    "compresion therapy",
    "pressure therapy", 
    "presure therapy",
    "normatek therapy",
    "normatec compreession therapy",
    "normatec compressioin therapy",
    "normatce compression therapy",
    "normatec compretion therapy",
    "nrmatec compression therapy",
    "normatec compreison therapy",
    "normateec compression therapy",
    "normatec compreesion therapy", 
    "normatec compressionn therapy",
    "normatec comprission therapy",
    "normatec compresssion therapy",
    "normatc compression therapy",
    "normatec comprezsion therapy",
    "normztec compression therapy",
    "normatec cmpression therapy"
  ],


  // Location specific corrections (no array needed, these map to location keys)
  stafford: "location",
  sugarland: "location",
  "sugar land": "location",
  southwest: "location",
  "sw freeway": "location",
  spring: "location",
  "red oak": "location",
  katy: "location",
  kingsland: "location",
  southfield: "location",
  michigan: "location",
  mi: "location",
  texas: "location",
  tx: "location",
  houston: "location",

  // Head Pain variations - Refactored to Array
  "Head Pain": [
    "head pain", // Included for completeness
    "headake",
    "migraines",
    "migrane",
    "hed pain",
    "hedache",
    "headace",
    "hed ake",
    "head ache",
    "headaik",
    "hedeik",
    "mygrane",
    "mygranes",
    "migren",
    "migrain",
    "cluster headache",
    "tension headache",
    "chronic headache",
    "tmj",
    "jaw pain",
    "facial pain",
  ],

  // Shoulder Pain variations - Refactored to Array
  "Shoulder Pain": [
    "shoulder",
    "shouder",
    "sholder",
    "shouldr",
    "shouldar",
    "sholuder",
    "shoulder pain", // Included for completeness
    "shouder pain",
    "sholder pain",
    "shouldr pain",
    "shouldar pain",
    "sholuder pain",
    "shoulder ache",
    "shouder ache",
    "frozen shoulder",
    "adhesive capsulitis",
    "shoulder bursitis",
    "shoulder strain",
    "shoulder impingement",
  ],
  "shoulder treatment": [
    // keep the intent separate for 'treatment' and 'therapy' variations.
    "shoulder treatment", // Included for completeness
    "shouder treatment",
  ],
  "shoulder therapy": [
    "shoulder therapy", // Included for completeness
    "shouder therapy",
  ],
  "rotator cuff": [
    "rotator cuff", // Included for completeness
    "rotater cuff",
    "rotatr cuff",
    "rotator cuf",
    "rotator coff",
    "roteater cuff",
    "rotatir kuff",
    "rotator tear",
    "rotator tear", //Duplicated in original list. Keeping for exact match with provided config
    "rotater cuff", //Duplicated in original list. Keeping for exact match with provided config
    "rotator cuff", //Duplicated in original list. Keeping for exact match with provided config
    "rotator cuff injuries", // new variations
    "rotator cuff injury", // new variations
  ],

  // Back Pain variations - Refactored to Array
  "Back Pain": [
    "back pain", // Included for completeness
    "backpain",
    "sore back",
    "backache",
    "bak pain",
    "bacak",
    "back ake",
    "bak ake",
    "lower back",
    "upper back",
    "mid back",
    "lower bak",
    "spine pain",
    "spinal pain",
    "back injury",
    "lumbago",
    "lumbar pain",
    "thoracic pain",
    "sciatica",
    "herniated disc",
    "slipped disc",
    "disk problem",
  ],

  // Neck Pain variations - Refactored to Array
  "Neck Pain": [
    "neck pain", // Included for completeness
    "neckpain",
    "sore neck",
    "nek pain",
    "neckache",
    "neak pain",
    "neck ake",
    "cervical pain",
    "stiff neck",
    "neck spasm",
    "tech neck",
    "text neck",
    "whiplash",
    "cervical strain",
    "pinched nerve neck",
    "cervical radiculopathy",
    "neck strain",
    "neck sprain",
  ],

  // Hip Pain variations - Refactored to Array
  "Hip Pain": [
    "hip pain", // Included for completeness
    "hippain",
    "hip ache",
    "hipache",
    "hipp pain",
    "hip problems",
    "hip issues",
    "hip bursitis",
    "hip arthritis",
    "hip osteoarthritis",
    "hip joint pain",
    "hip replacement",
    "groin pain",
    "hip flexor",
    "trochanteric pain",
    "hip impingement",
  ],

  // Elbow Pain variations - Refactored to Array
  "Elbow Pain": [
    "elbow pain", // Included for completeness
    "elbowpain",
    "elbow ache",
    "elbowache",
    "elbo pain",
    "elbrow pain",
    "elbowe pain",
    "tennis",
    "tennis elbow",
    "golfers elbow",
    "lateral epicondylitis",
    "medial epicondylitis",
    "elbow tendonitis",
    "elbow tendinitis",
    "cubital tunnel",
    "elbow bursitis",
    "elbow arthritis",
    "elbow arthritis",
  ],

  // Pelvic Floor variations - Refactored to Array
  "Pelvic Floor": [
    "pelvic floor", // Included for completeness
    "pelvicfloor",
    "pelvic flooor",
    "pelvic florr",
    "pelvic fold",
    "pelvic therapy",
    "pelvic floor therapy",
    "pelvic pain",
    "incontinence",
    "bladder control",
    "urinary leakage",
    "pelvic dysfunction",
    "pelvic muscles",
  ],

  // Hand/Wrist Pain variations - Refactored to Array (already done in previous response)
  "Hand/Wrist Pain": [
    "hand/wrist pain", // Included for completeness, although redundant as key itself is the target
    "handwristpain",
    "hand wrist pain",
    "wristpain",
    "wrist pain",
    "hand ache",
    "wrist ache",
    // "carpal tunnel",
    // "carpel tunnel",
    // "carpal syndrome",
    "wrist tendonitis",
    "trigger finger",
    "wrist sprain",
    "hand arthritis",
    "hand tendonitis",
    "finger pain",
    "thumb pain",
    "de quervains",
    "dequervains",
  ],

  // Knee Pain variations - Refactored to Array
  "Knee Pain": [
    "knee pain", // Included for completeness
    "kneepain",
    "knee ache",
    "kneeache",
    "nee pain",
    "ne pain",
    "knee injury",
    "knee arthritis",
    "runner knee",
    "runners knee",
    "patellofemoral",
    "knee osteoarthritis",
    "acl injury",
    "mcl injury",
    "acl tear",
    "meniscus",
    "meniscus tear",
    "knee replacement",
    "knee rehab",
    "patellar pain",
    "knee tendonitis",
    "kneepain", // Duplicates - Keeping for original fidelity
    "knee ache", // Duplicates - Keeping for original fidelity
    "kneeache", // Duplicates - Keeping for original fidelity
  ],

  // Foot/Ankle Pain corrections - Refactored to Array
  "Foot/Ankle Pain": [
    "footanklepain",
    "foot ankle pain", 
    "footache",
    "anklepain",
    "ankle ache",
    "ankleache",
    "foot ache",
  ],

  // Parking variations 
  "parking": [
    "parking",
    "park",
    "parking spot",
    "parking space",
    "parking lot",
    "parking area",
    "carpark",
    "car park",
    "valet",
    "valet parking",
    "handicap parking",
    "disabled parking",
    "accessible parking",
    "patient parking",
    "visitor parking",
    "free parking",
    "parking available",
    "where to park",
    "can i park",
    "parking garage"
  ],


  // Appointment related (no array needed, direct mapping)
  appointment: "appointment",
  appoitment: "appointment",
  apointment: "appointment",
  apoinment: "appointment",
  appointmnt: "appointment",
  appt: "appointment",
  apt: "appointment",
  booking: "appointment",

  // Schedule related (no array needed, direct mapping or compound value)
  schedule: "schedule",
  schedl: "schedule",
  schedual: "schedule",
  shedule: "schedule",
  scedule: "schedule",
  scehdule: "schedule",
  skdule: "schedule",
  "schedl appt": "schedule appointment",
  "book appt": "schedule appointment",
  "make appt": "schedule appointment",
  "set up appt": "schedule appointment",
  "reserv appt": "schedule appointment",

  // Services related (no array needed, direct mapping)
  service: "service",
  services: "service",
  servis: "service",
  servise: "service",
  servicies: "service",
  srvices: "service",
  servces: "service",
  servics: "service",
  "therapy servce": "service",
  "rehab service": "service",

  // Insurance related (no array needed, direct mapping)
  insurance: "insurance",
  insuranse: "insurance",
  insurence: "insurance",
  insurnce: "insurance",
  insuranc: "insurance",
  insurace: "insurance",
  insrance: "insurance",
  insurnc: "insurance",
  "medical insurance": "insurance",
  "health insurance": "insurance",
  coverage: "insurance",
  covrage: "insurance",
  bcbs: "insurance",
  aetna: "insurance",
  cigna: "insurance",
  united: "insurance",
  medicare: "insurance",
  medicaid: "insurance",
  "blue cross": "insurance",
  "blue shield": "insurance",
  uhc: "insurance",

  // Location related (no array needed, direct mapping)
  office: "office",
  offise: "office",
  ofise: "office",
  ofice: "office",
  offic: "office",
  ofc: "office",
  location: "location",
  locatoin: "location",
  lokation: "location",
  locaton: "location",
  locatn: "location",
  address: "address",
  addres: "address",
  adress: "address",
  adres: "address",
  addresse: "address",
  place: "location",
  where: "location",
  clinic: "location",
  clink: "location",
  clnic: "location",
  clinc: "clinlocationic",
  clinik: "physical therapy",
  facility: "physical therapy",
  faciltiy: "physical therapy",
  facilty: "physical therapy",
  faciliti: "physical therapy",
  facility: "physical therapy",

  // Hours related (no array needed, direct mapping)
  hours: "hours",
  time: "hours",
  working: "hours",
  "work hours": "hours",
  "open hours": "hours",
  "hours open": "hours",
  "operation hours": "hours",
  "business hours": "hours",
  "local visit": "hours",
  tim: "hours",
  clock: "hours",
  tame: "hours",
  tam: "hours",
  "when open": "hours",
  "when close": "hours",
  opening: "hours",
  closing: "hours",
  "when r u open": "hours",
  "when are you open": "hours",
  "schedule hours": "hours",
};

export const BUTTON_OPTIONS = {
  main: [
    { text: "📅 Book Appointment", type: "appointment" },
    { text: "👩‍⚕️ Speak with Therapist", type: "staff" },
    { text: "⚙️ Our Services", type: "service" },
    { text: "❓ Ask PT Questions", type: "questions" },
    { text: "🏥 Clinic Info", type: "locations" },
  ],
  painAreas: [], // This will be initialized by generatePainAreaButtons
};

export function generatePainAreaButtons(detectedAreas = null) {
  if (detectedAreas && detectedAreas.length > 0) {
    return detectedAreas.map(({ key, data }) => ({
      text: `${data.icon} ${data.display}`,
      type: "pain",
      area: key,
      description: data.description,
    }));
  }

  return Object.entries(PAIN_AREAS)
    .slice(0, 10)
    .map(([key, data]) => ({
      text: `${data.icon} ${data.display}`,
      type: "pain",
      area: key,
      description: data.description,
    }));
}

// Initialize pain areas in BUTTON_OPTIONS
BUTTON_OPTIONS.painAreas = generatePainAreaButtons();
